# Generated by Django 5.2.1 on 2025-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
